version: "3"
services:
  neo4jdb:
    image: neo4j
    container_name: neo4j-springboot
    #    restart: always
    volumes:
      - $HOME/data/:/data
    ports:
      - 7474:7474
      - 7687:7687

  rating-service:
    build: .
    ports:
      - 8080:8081
    depends_on:
      - neo4jdb
    links:
      - neo4jdb
    #    restart: always
    expose:
      - 8080